### PR TITLE
postmark mixin for tornado

### PR DESCRIPTION
**Pull request by tigrus**
Based on comment: https://github.com/themartorana/python-postmark/issues/51

### CODE REVIEW

**Comment by nicholasserra** [comment]
Any info on how this should be used?

**Comment by nicholasserra** [comment]
A section in the README, similar to the Django instructions, would be useful.

**Comment by tigrus** [comment]
One second, will add instructions

**Comment by nicholasserra** [comment]
Awesome thank you. I'll take a final look this weekend.

**Pull request merged**
