### PR TITLE
added in utf8 into decode to remove UnicodeError

### PR DESCRIPTION
**Pull request by bendtheji**
This is based on issue #60

### CODE REVIEW

**Comment by nicholasserra** [comment]
Wondering if there's a regression test we can write for this.

**Comment by bendtheji** [comment]
Hi @nicholasserra  what do you mean by regression test? As in, what do you have in mind for regression testing

**Comment by nicholasserra** [comment]
A failing test that shows the bug, which is fixed by your patch.

**Comment by bendtheji** [comment]
So what I did is that I had input a unicode representing chinese characters into a variable. The variable is called chinese.

In [7]: chinese
Out[7]: u'\u7f2a\u5efa\u5175'

Using the PMMail constructor in the core.py file in the API,

mail_object = PMMail(api_key=PostmarkAPIKey, sender="sendername<senderemail@domain.com>", to=**chinese** + "<receipient@gmail.com>", cc="", subject="failing test", html_body="Hello there", track_opens=True,attachments=[],reply_to="senderemail@domain.com")

Then I sent the email:
r = mail_object.send()

This is the error I received:

UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-11-5a2d27b0a934> in <module>()
----> 1 r = mail_object.send()

/home/ubuntu/process/app/util/core.pyc in send(self, test)
    447             #print 'sending request to postmark: %s' % json_message
    448             result = urlopen(req)
--> 449             jsontxt = result.read().decode()
    450             result.close()
    451             if result.code == 200:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 7: ordinal not in range(128)


Now, I also tried encoding the chinese variable using encode('utf8') like so:
encoded = chinese.encode('utf8')

In [8]: encoded
Out[8]: '\xe7\xbc\xaa\xe5\xbb\xba\xe5\x85\xb5'

And putting it in the PMMail constructor:
mail_object = PMMail(api_key=PostmarkAPIKey, sender="sendername<senderemail@domain.com>", to=**encoded** + "<receipient@gmail.com>", cc="", subject="failing test", html_body="Hello there", track_opens=True,attachments=[],reply_to="senderemail@domain.com")

And got the same error:
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-13-5a2d27b0a934> in <module>()
----> 1 r = mail_object.send()

/home/ubuntu/process/app/util/core.pyc in send(self, test)
    447             #print 'sending request to postmark: %s' % json_message
    448             result = urlopen(req)
--> 449             jsontxt = result.read().decode()
    450             result.close()
    451             if result.code == 200:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 7: ordinal not in range(128)


Now using a modified core.py file whereby I change the code on line 449 from 
jsontxt = result.read().decode() 

to 

jsontxt =result.read().decode('utf8') 

Using the same format for the constructor, and passing in the chinese variable, I got no errors:

In [9]: r = mail_object.send()

In [10]: r                      
Out[10]: True

Same results when I pass in the encoded variable:
In [14]: r = mail_object.send()

In [15]: r
Out[15]: True

**Comment by nicholasserra** [comment]
Gotcha. Can you create a unit test for that, and add it to the test suite? Let me know if that's something you're unfamiliar with. I can probably write something if so.

**Comment by bendtheji** [comment]
Hey Nicholas,

Apologies but I am unfamiliar with that. Thanks for helping out!

**Comment by bendtheji** [comment]
Hey @nicholasserra , sorry to bother you but are there any updates?

**Comment by nicholasserra** [comment]
No bother :) No updates yet. Need to write some tests for this. Fix should be fine, but I want to make sure it doesn't break anything.

**Comment by bendtheji** [comment]
Ah I see i see. Once again, thanks so much for the help :)

**Comment by bendtheji** [comment]
Hey @nicholasserra sorry to bother you. This is actually quite an urgent issue on our end because currently when we try to send out an email with special characters, what happens is that although the email manages to send out, we won't be able to get the message ID of the email. 

446: try:
447:            #print 'sending request to postmark: %s' % json_message
448:            result = urlopen(req)
449:           jsontxt = result.read().decode()
450:            result.close()
451:            if result.code == 200:
452:                self.message_id = json.loads(jsontxt).get('MessageID', None)
453:                return True
454:            else:
455:                raise PMMailSendException('Return code %d: %s' % (result.code, result.msg))

As you can see, the error occurs on line 449 and the program gets cut off there and it never goes to line 452, which means we never get the message id of the email. For our side, we need the message id as we store a table containing our sent emails and if a webhook were to be sent to us, we would use the message id as a reference to update the statuses of these emails on the database. 

I had brought up this issue to Postmark support, and also much thanks to them, and @mgornik (Milan Gornik) had also posted a solution here:
https://github.com/mgornik/python-postmark/blob/master/postmark/core.py

which also implements the decode('utf-8') on line 449. However, we would prefer if we could use the code from the main library. 

Therefore, I was wondering if this issue could be resolved as soon as possible because it's becoming quite a huge issue on our end. Sorry for the trouble.

**Comment by bendtheji** [comment]
Hi, thanks so much for all the help! @nicholasserra  @mgornik @atheken 

We are now able to get the messageID of the email with special characters as parameters. Gonna delete the branch now. Thanks again for the help :)

**Pull request merged**
